### ISSUE TITLE
Val cannot be reassigned in kotlin

### ISSUE THREAD

**Issue by dariushEm** [franmontiel/LocaleChanger#12]
override fun attachBaseContext(newBase: Context?) {
         newBase = LocaleChanger.configureBaseContext(newBase)
        super.attachBaseContext(newBase)
    }
}

newBase  : Val cannot be reassigned in kotlin

**Comment by patentfm** [comment]
try pass like this  super.attachBaseContext(LocaleChanger.configureBaseContext(newBase))

**Comment by patentfm** [comment]
resolved, may be closed ;)
