### ISSUE TITLE
AndroidX support

### ISSUE THREAD

**Issue by OmarAliSaid** [franmontiel/LocaleChanger#13]
could u please support AndroidX for the library .. thanks

**Comment by hendrawd** [comment]
@OmarAliSaid According to https://developer.android.com/jetpack/androidx#using_androidx, you can set both of below properties in your project-level `gradle.properties` file to `true`
```gradle
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by franmontiel** [comment]
AndroidX support added on v1.0
