### ISSUE TITLE
Change Language with Application-Level Context

### ISSUE THREAD

**Issue by hendrawd** [franmontiel/LocaleChanger#16]
This library will not work if I use the application context to get the string. 
I'm planning to call `LocaleChanger.configureBaseContext()` directly from my `Application` since I think it can be used globally through my application without passing any context from activity.
From the documentation of the function,
```java
/**
 * This method should be used inside the Activity attachBaseContext.
 * The returned Context should be used as argument for the super method call.
 *
 * @param context
 * @return the resulting context that should be provided to the super method call.
 */
public static Context configureBaseContext(Context context) {
    return delegate.configureBaseContext(context);
}
```
It stated that `This method should be used inside the Activity attachBaseContext` and not mentiong about application context. 

My question is it safe that I created helper function from my application
```java
// inside Application class
public Context getContextForLanguage() {
    return LocaleChanger.configureBaseContext(this);
}
```
and use that helper funtion to get the string from somewhere else? (Like below)
```kotlin
(application as MyApplication).getContextForLanguage().getString(R.string.something)
```
What are the drawbacks of this approach?

**Comment by franmontiel** [comment]
As far as I know should be able to use your getContextForLanguage method without any problems
