### ISSUE TITLE
Delegate is null

### ISSUE THREAD

**Issue by alashow** [franmontiel/LocaleChanger#3]
I'm getting this exception on orientation changes:
```ruby
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.franmontiel.localechanger.LocaleChangerDelegate.onConfigurationChanged()' on a null object reference com.franmontiel.localechanger.LocaleChanger.onConfigurationChanged(LocaleChanger.java:126)
my.app.App.onConfigurationChanged(App.java:86)
android.app.ActivityThread.performConfigurationChanged(ActivityThread.java:4909)
```

**Comment by franmontiel** [comment]
Hi, have you called LocaleChanger.initialize before from the Application onCreate?

**Comment by alashow** [comment]
Yes. 
BTW, It doesn't always crash.

**Comment by alashow** [comment]
I think I know what it is.

I'm using [LeakCanary](https://github.com/square/leakcanary) so I'm initializing LocalChanger if the process is not LeakCanary's analyzer process.

When a leak happens and orientation changes, then`App#onConfigurationChanged` of analyzer process gets called and the delegate is null.
I fixed it by not notifying LocalChanger about configuration changes if in LeakCanary's analyzer process.

Do you think adding a null check for the delegate is practical for issues like this?

**Comment by franmontiel** [comment]
No plans for covering that use case
