### ISSUE TITLE
Activity does not automatically re-create

### ISSUE THREAD

**Issue by tcqq** [franmontiel/LocaleChanger#7]
When the system language changes, I use the following code to initialize, But when I return to the previous Activity, Activity does not automatically re-create, Causes the language not to be fully updated. **This is because "previousLocale" is empty**, So this also leads to another problem. When I change the language of the system and then return to the application, the application does not automatically recreate the activity, When you return to the app for the second time, the activity is re-created.

**The second time back to the APP language will be changed is because: When the language changes and back to the application, then first call "onResume" but now the system language configuration is not updated`Locale.setDefault(newLocale);`, so the activity is not reset, , then call "SampleApplication"-> "onConfigurationChanged", then The system language config was updated, So when you first return to the app, the language will not be updated. When you return to the app for the second time, the activity will be recreated and the language will be updated.**

![image](https://user-images.githubusercontent.com/10644057/38459987-c31e1894-3ae3-11e8-9e1c-762b760b08be.png)

```
public class LocaleChangeReceiver extends BroadcastReceiver {

    public final static String INTENT = "android.intent.action.LOCALE_CHANGED";

    @Override
    public void onReceive(Context context, Intent intent) {
        if (intent.getAction().equals(INTENT)) {
            LocaleChanger.resetLocale();
        }
    }
}
```

**Comment by devangichhatbar** [comment]
The same issue occurs. Please solve this issue.

**Comment by tcqq** [comment]
@devangichhatbar Look at this example, it solves the above problem. https://github.com/tcqq/LocaleSwitcher

**Comment by franmontiel** [comment]
On the Activity that changes the language, you need to manually call `ActivityRecreationHelper.recreate` method.
For automatic recreation of activities that were on the back stack you should have all your Activities calling the methods `ActivityRecreationHelper.onResume` and `ActivityRecreationHelper.onDestroy` in `onResume` and `onDestroy`.

If you follow those steps Activity recreation shouldn't be a problem
